1. Write a Python program to create a Balanced Binary Search Tree (BST) using an array
(given) elements where array elements are sorted in ascending order.

In [124]:
class Node:
    
    def __init__(self, root):
        self.value = root
        self.left = None
        self.right = None
    
def sort_to_bst(nums):

    if not nums:
        return

    mid_val = len(nums) // 2
    node = Node(nums[mid_val])
    node.left = sort_to_bst(nums[:mid_val])
    node.right = sort_to_bst(nums[mid_val+1:])
    return node
    
def printPreOrder(root):
    if not root:
        return
    print(root.value)
    printPreOrder(root.left)
    printPreOrder(root.right)
    
def printInorder(root): 
    if root:  
        printInorder(root.left) 
        print(root.value)
        printInorder(root.right) 
        
def printPostorder(root):   
    if root: 
        printPostorder(root.left) 
        printPostorder(root.right) 
        print(root.value)
        
results = [1, 2, 3, 4, 5, 6, 7]
node = sort_to_bst(results)
printPreOrder(node)

4
2
1
3
6
5
7


2. Write a Python program to find the closest value of a given target value in a given nonempty Binary Search Tree (BST) of unique values.

In [125]:
def closest_value(root, target):
    if root == None: return
    if target is None: return
    
    a = root.value
    
    if(target < a):
        kid = root.left
    else:
        kid = root.right
    
    if not kid:
        return a
    
    b = closest_value(kid, target)
    
    keya = abs(target-a)
    keyb = abs(target-b)
    
    if keya < keyb:
        return a
    else:
        return b

In [126]:
solution = closest_value(node, 0)
print(solution)

1


3. Write a Python program to check whether a given a binary tree is a valid binary search
tree (BST) or not

In [127]:
# Python program to check if a binary tree is bst or not 
  
INT_MAX = 4294967296
INT_MIN = -4294967296

def is_BST(root, min_value, max_value):
    
    if root is None:
        return True
    
    if (root.value > min_value & root.value < max_value):
        return True
    else:
        return False
    
    return (is_BST(root.left, min_value, root.value) and is_BST(root.right, root.value, max_value))
    
def isBinarySearchTree(root):
    return (is_BST(root, INT_MIN, INT_MAX))

In [128]:
isBinarySearchTree(node)

True

4. Write a Python program to delete a node with the given key in a given Binary search
tree (BST).

In [129]:
def minValueNode(node):
    
    current = node
    
    while(current.left is not None):
        current = current.left
        
    return current

In [130]:
def delete_Node(root, target):
    
    if root == None: return
    elif root.value > target:
        root.right = delete_Node(root.right, target)
    elif root.value < target:
        root.left = delete_Node(root.left, target)
    else:
        # If there is no child
        # Node with only one child or no child 
        if root.left is None:
            temp = root.right
            root = None
            return temp
        
        elif root.right is None:
            temp = root.left
            root = None
            return temp
        
        # 1)You need to find the min in the right subnode
        # or the max in the left subnode
        # 2) Copy the value in targetted node
        # 3) Delete the duplicate form right-subtree
        
        # Node with two children: Get the inorder successor 
        # (smallest in the right subtree) 
        temp = minValueNode(root.right) 
  
        # Copy the inorder successor's content to this node 
        root.value = temp.value 
  
        # Delete the inorder successor 
        root.right = delete_Node(root.right , temp.value) 
  
    return root

In [131]:
printPreOrder(node)

4
2
1
3
6
5
7


In [132]:
new_node = delete_Node(node, 4)

In [133]:
printPreOrder(new_node)

5
2
1
3
6
5
7


Inserting an element into a binary search tree

In [134]:
# A utility function to insert a new node with given key in BST 
def insert(node, key): 
  
    # If the tree is empty, return a new node 
    if node is None: 
        return Node(key) 
  
    # Otherwise recur down the tree 
    if key < node.value: 
        node.left = insert(node.left, key) 
    else: 
        node.right = insert(node.right, key) 
  
    # return the (unchanged) node pointer 
    return node 

5. Write a Python program to find the kth smallest element in a given a binary search tree.

In [135]:
def findKthSmallestElement(root, k):
    
    current = root
    kth_value = k
    
    if root is None:
        return
    
    while(current.left != None):
        kth_value = kth_value - 1
        current = current.left
        
        if(k == 0):
            return root.value
    
    return current.value

In [136]:
a = findKthSmallestElement(node, 2)

In [137]:
print(a)

1


Create a binary tree with these properties

In [138]:
tree = Node(11)
tree.left = Node(8)
tree.right = Node(16)
tree.left.left = Node(5)
tree.left.right = Node(10)

tree.right = Node(16)
tree.right.right = Node(18)

In [139]:
printPreOrder(tree)

11
8
5
10
16
18


In [140]:
class FamilyTree:
    
    def __init__(self, x):
        self.father = x
        self.child = []
        
    def setChildren(self, values):
        for i in values:
            self.child.append(i)

In [141]:
family = FamilyTree(['Kalu', 'Mary'])
family.setChildren(['David', 'Nnanna', 'Amarachi'])

In [142]:
family.father

['Kalu', 'Mary']

In [143]:
second = FamilyTree([family.child[0], 'Ray'])
second.setChildren(['David', 'Miracle'])

In [144]:
second.child

['David', 'Miracle']

In [145]:
array = [50, 76, 21, 4, 32, 100, 64, 52]
array.sort()

In [146]:
test_tree = sort_to_bst(array)

In [147]:
test_tree.right.value

76

In [148]:
inOrder(test_tree)

4
21
32
50
52
64
76
100


In [149]:
new_tree = delete_Node(test_tree, 100)

In [150]:
inOrder(test_tree)

4
21
32
50
52
64
76
100


In [151]:
printPreOrder(test_tree)

52
32
21
4
50
76
64
100


Breath First Search, binary tree

In [152]:
def breadth_first_search(root):
    to_visit = []
    if root is None:
        return
    
    to_visit.append(root)
    
    while to_visit:
        current = to_visit.pop(0)
        print(current.value)
        if current.left:
            to_visit.append(current.left)
        if current.right:
            to_visit.append(current.right)

In [153]:
breadth_first_search(node) # bfs

5
2
6
1
3
5
7


In [186]:
printPreOrder(node) #dfs

5
2
1
3
6
5
7


### Topological sort

In [336]:
from collections import defaultdict

In [344]:
adjacent_list = {'a' : ['d'], 
                'b' : ['d'],
                'c' : ['e'],
                'd' : ['e'],
                'e' : []}

In [345]:
visited_list = defaultdict()
visited_list['a'] = False
visited_list['b'] = False
visited_list['c'] = False
visited_list['d'] = False
visited_list['e'] = False

output_stack = []

In [346]:
def topology_sort(vertex):
    
    if not visited_list[vertex]:
        visited_list[vertex] = True
        for neighbour in adjacent_list[vertex]:
            topology_sort(neighbour)
        output_stack.insert(0, vertex)

In [348]:
for vertex in visited_list:
    topology_sort(vertex)

In [349]:
output_stack

['c', 'b', 'a', 'd', 'e']

### Merge sort

In [300]:
def mergeSort(x):
   
    if len(x) > 1:
        mid = len(x) // 2
    
        left = x[:mid]
        right = x[mid:]
        
        mergeSort(left)
        mergeSort(right)
        
        i = j = k = 0

        while(i < len(left) and j < len(right)):
            
            if(left[i] < right[j]):
                x[k] = left[i]
                i = i + 1
            else:
                x[k] = right[j]
                j = j + 1

            k = k + 1

        while (i < len(left)):
            x[k] = left[i]
            i = i + 1
            k = k + 1

        while (j < len(right)):
            x[k] = right[j]
            j = j + 1
            k = k + 1
    
    return x

dummy = [16, 2, 5, 8, 5, 5, 7, 1, 0, 6]
a = mergeSort(dummy)
a

[0, 1, 2, 5, 5, 5, 6, 7, 8, 16]

### Quick sort

In [301]:
def choosePivot(arr, low, high):
    from random import randrange
    random = randrange(low, high)
    return random

In [302]:
def partition(arr, low, high):
    
    i = (low-1)
    pivot = arr[high]
    
    for j in range(low, high):
        
        if arr[j] <= pivot:
            
            i = i + 1
            arr[i], arr[j] = arr[j], arr[i]
            
    arr[i+1], arr[high] = arr[high], arr[i+1]
    return (i+1)

In [307]:
def quickSortUtil(array, left, right):
    if(left >= right):
        return array
    else:
        i = choosePivot(array, left, right)
        array[i], array[right] = array[right], array[i]
        pivot = partition(array, left, right)
        
        quickSortUtil(array, left, pivot-1)
        quickSortUtil(array, pivot+1, right)
        
        return array
    
def quickSort(array):
    return (quickSortUtil(array, 0, len(array)-1))

In [308]:
dummy = [16, 2, 5, 8, 5, 5, 7, 1, 0, 6]
b = quickSort(dummy)
b

[0, 1, 2, 5, 5, 5, 6, 7, 8, 16]

### Strassan Algorithm

In [367]:
x = np.random.randint(0, 10, (8, 8)) # Created an array 1
y = np.random.randint(0, 10, (8, 8)) # Created an array 2

print(x) # print
print(y)

[[8 4 3 1 8 3 8 0]
 [6 1 4 2 3 6 2 2]
 [0 5 5 0 1 0 6 2]
 [8 6 4 9 1 5 7 0]
 [3 5 8 7 5 0 7 5]
 [8 8 0 2 8 8 7 8]
 [4 5 7 8 2 5 1 6]
 [6 5 7 8 9 8 0 3]]
[[2 2 6 3 5 0 0 0]
 [6 9 6 7 0 0 8 5]
 [3 6 9 6 5 9 3 2]
 [1 4 3 0 1 5 0 8]
 [0 0 1 2 6 5 0 3]
 [5 2 3 4 4 1 1 6]
 [3 0 7 1 9 9 7 0]
 [0 3 8 0 3 4 0 6]]


In [371]:
def splitMatrix(x):
    row, col = x.shape
    return x[:row//2, :col//2], x[:row//2, col//2:], x[row//2:, :col//2], x[row//2:, col//2:]

def strassanAlgorithm(x, y):
  
    if(len(x) == 1):
        return x * y
    
    a, b, c, d = splitMatrix(x)
    e, f, g, h = splitMatrix(y)

    p1 = strassanAlgorithm(a, f-h)
    p2 = strassanAlgorithm(a + b, h)
    p3 = strassanAlgorithm(c + d, e)
    p4 = strassanAlgorithm(d, g - e)
    p5 = strassanAlgorithm(a + d, e + h)
    p6 = strassanAlgorithm(b - d, g + h)
    p7 = strassanAlgorithm(a - c, e + f)


    x1 = p5 + p4 - p2 + p6
    x2 = p1 + p2
    x3 = p3 + p4
    x4 = p1 + p5 - p3 - p7

    return np.vstack((np.hstack([x1, x2]), np.hstack([x3, x4])))


a = strassanAlgorithm(x, y)
a

array([[ 89,  80, 175, 106, 188, 147, 100,  76],
       [ 68,  71, 135,  81, 118,  93,  40,  86],
       [ 63,  81, 134,  73,  91, 112,  97,  50],
       [119, 140, 212, 119, 158, 154, 114, 143],
       [ 88, 142, 235, 109, 170, 215, 113, 142],
       [127, 136, 247, 135, 209, 153, 121, 176],
       [ 95, 155, 213, 114, 122, 151,  73, 175],
       [111, 156, 210, 145, 168, 168,  69, 196]])

### Straight forward approach

In [373]:
def straightForwardApproach(x, y):
    result = [] # final result
    for i in range(len(x)):

        row = [] # the new row in new matrix
        for j in range(len(y)):
            product = 0 # the new element in the new row
            for k in range(len(x[i])):
                product += x[i][k] * y[k][j]
            row.append(product) # append sum of product into the new row
        result.append(row) # append the new row into the final result
    return result

### Integer Recursive Multiplication

In [335]:
def recursiveAlgorithm(x, y):
    if (x < 10 and y < 10):
        return x * y
    else:
        x = str(x)
        y = str(y)
        n = max(len(x), len(y))
        
        j = n // 2

        a = int(x) / 10**(j) # first half (1)
        b = int(x) % 10**(j) # second half (1)

        c = int(y) / 10**(j) # first half (2)
        d = int(y) % 10**(j) # second half (2)

        a = int(a)
        b = int(b)
        c = int(c)
        d = int(d)
        
        ac = recursiveAlgorithm(a, c)
        ad = recursiveAlgorithm(a, d)
        bc = recursiveAlgorithm(b, c)
        bd = recursiveAlgorithm(b, d)
        
        return (ac * 10 ** (2*j)) + (10 ** j * (ad+bc))+ bd
    
x = 1234
y = 2333

a = recursiveAlgorithm(x, y)
a

2878922

In [ ]:
def karaturbaAlgorithm(x, y):
  # If the len of the a & b == 1, then just return the base case.
  if(x < 10 and  y < 10):
    return x * y
  else:
    # Length of the digits
    x = str(x)
    y = str(y)
    n = max(len(x), len(y))
   
    j = n // 2
 
    a = int(x) / 10**(j) # first half (1)
    b = int(x) % 10**(j) # second half (1)

    c = int(y) / 10**(j) # first half (2)
    d = int(y) % 10**(j) # second half (2)
    
    a = int(a)
    b = int(b)
    c = int(c)
    d = int(d)
    
    p = a + b
    q = c + d
    # recursively compute the first and second half of the array
    ac = karaturbaAlgorithm(a, c)
    bd = karaturbaAlgorithm(b, d)
    pq = karaturbaAlgorithm(p, q)
    adbc = pq - ac - bd
    
    return ac * 10**(2*j) +  (10**j * adbc) + bd

In [334]:
import numpy as np
a = np.array([[1, 2],[2, 3]])
a.shape

(2, 2)

### Graphs

In [354]:
def dijsktra(graph, initial):
    visited = {initial: 0} #Mark all nodes unvisited,set the initial node distance to 0
    path = {}

    nodes = set(graph.nodes)#set of unvisited vertices

    while nodes: #while there is an element in the unvisited list
        min_node = None #Assigning a value of None to a variable is one way to reset it to its original, empty state.
        for node in nodes:
            if node in visited:
                if min_node is None:
                    min_node = node #min node becomes the the node from the ser of unvisited nodes
                elif visited[node] < visited[min_node]: #if the distance of the current node is less then the previous
                    min_node = node #finding the minimum distance node (updating the previous value)

        if min_node is None:
            break

        nodes.remove(min_node)#removing the minimum node from the list of unvisited
        current_weight = visited[min_node] #distance from the minimum node

        for edge in graph.edges[min_node]: #for all edges
            weight = current_weight + graph.distances[(min_node, edge)] #calculation if the distances
            if edge not in visited or weight < visited[edge]: #updating only when the node is not in the list 
                    #of visited or current weight is less then the previous
                visited[edge] = weight
                path[edge] = min_node

    return visited, path

In [355]:
class Graph:#Class definition
    def __init__(self):
        self.nodes = set()
        self.edges = defaultdict(list)#A defaultdict works exactly like a normal dict, but it is initialized with 
        #a function (“default factory”) that takes no arguments and provides the default value for a nonexistent key.
        self.distances = {}

    def add_node(self, value):
        self.nodes.add(value)

    def add_edge(self, from_node, to_node, distance):
        self.edges[from_node].append(to_node)
        self.edges[to_node].append(from_node)
        self.distances[(from_node, to_node)] = distance
        self.distances[(to_node, from_node)] = distance


In [356]:
from collections import defaultdict
g = Graph()
g.add_node('A')
g.add_node('B')
g.add_node('C')
g.add_node('D')
g.add_node('E')

g.add_edge('A', 'B', 6)
g.add_edge('A', 'D', 1)
g.add_edge('B', 'A', 6)
g.add_edge('B', 'D', 2)
g.add_edge('B', 'E', 2)
g.add_edge('C', 'B', 5)
g.add_edge('C', 'E', 5)
g.add_edge('D', 'A', 1)
g.add_edge('D', 'B', 2)
g.add_edge('D', 'E', 1)
g.add_edge('E', 'B', 2)
g.add_edge('E', 'C', 5)
g.add_edge('E', 'D', 1)



print(dijsktra(g, 'A'))

({'A': 0, 'B': 3, 'D': 1, 'E': 2, 'C': 7}, {'B': 'D', 'D': 'A', 'E': 'D', 'C': 'E'})


### Algorithms

In [358]:
def searchMatrix(arr1, arr2): 
  
    for i in range(len(arr1)): 
        for j in range(len(arr2)): 
            if arr1[i] == arr2[i]:
                print('Element is found with index', i)
                return True 
  
    return False

In [ ]:
def searchArray(arr, x): 
  
    for i in range(len(arr)): 
  
        if arr[i] == x:
            Print('Element is found with index', i)
            return True 
  
    return False

In [361]:
def fib(n):
    if n == 1: # first month
        return 1
    elif n == 2: # second month
        return 1
    else: # Recursive calls
        return fib(n-1) + fib(n-2)
fib(7)

13

In [362]:
def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n-1)